twitter:
    keys:
        consumer_key: YOUR_TWITTER_CONSUMER_KEY
        consumer_secret: YOUR_TWITTER_CONSUMER_SECRET
        oauth_access_token: YOUR_TWITTER_ACCESS_TOKEN
        oauth_access_token_secret: YOUR_TWITTER_ACCESS_TOKEN_SECRET
    tweets_limit: 500
    average_count: true